Add Gentoo, refactor a bit, fix typo

diff --git a/pacman b/pacman
--- a/pacman
+++ b/pacman
@@ -61,9 +61,6 @@ INSTALL
     $ wget https://github.com/icy/pacapt/raw/master/pacman -O /usr/local/bin/pacman
     $ chmod 755 /usr/local/bin/pacman
 
-  If you're running Gentoo, you need to install 'eix' first:
-    # emerge eix
-
   This script shouldn't be installed on an Arch-based system.
 
 SYNTAX
@@ -138,14 +135,20 @@ EOF
 ### Helpers
 ###
 
+_exists() {
+  [ -f "$1" ]
+}
+
 _exec_() {
   local _type="$1"
   shift
   [ "$_OSTYPE" = "$_type" ] || return 0
   _error "Going to execute: $* $_VERBOSE $_FORCE"
-#  eval "$* $_VERBOSE $_FORCE"
-  # DEBUG
-  echo "$* $_VERBOSE $_FORCE"
+  eval "$* $_VERBOSE $_FORCE"
+  # # DEBUG
+  # echo ""
+  # echo "== $* $_VERBOSE $_FORCE =="
+  # echo ""
 }
 
 
@@ -181,7 +184,7 @@ _OSTYPE_detect() {
 _OSTYPE_detect
 
 ## DEBUG
-echo "OS Type: $_OSTYPE\n"
+echo "OS Type: $_OSTYPE"
 
 case "$_OSTYPE" in
   "PACMAN")
@@ -212,9 +215,11 @@ while getopts "URQShfvlumyispqwco" opt; do
       fi
       _POPT="$opt"
       ;;
+
     s|l|i|p|q|o|m)
         _SOPT="$opt"
       ;;
+
     u)
       if [ "${_SOPT:0:1}" = "y" ]; then
         _SOPT="uy"
@@ -222,6 +227,7 @@ while getopts "URQShfvlumyispqwco" opt; do
         _SOPT="u"
       fi
       ;;
+
     y)
       if [ "${_SOPT:0:1}" = "u" ]; then
         _SOPT="uy"
@@ -229,6 +235,7 @@ while getopts "URQShfvlumyispqwco" opt; do
         _SOPT="y"
       fi
       ;;
+
     c)
       if [ "${_SOPT:0:2}" = "cc" ]; then
         _SOPT="ccc"
@@ -238,6 +245,7 @@ while getopts "URQShfvlumyispqwco" opt; do
         _SOPT="$opt"
       fi
       ;;
+
     w)
         case "$_OSTYPE" in
           "DPKG") _TOPT="-d" ;;
@@ -253,6 +261,7 @@ while getopts "URQShfvlumyispqwco" opt; do
           "PORTAGE") _TOPT="--fetchonly" ;;
         esac
       ;;
+
     f)
         case "$_OSTYPE" in
           "DPKG")     _FORCE="-f --force-yes" ;;
@@ -261,7 +270,9 @@ while getopts "URQShfvlumyispqwco" opt; do
           *)          _FORCE="-y" ;;
         esac
       ;;
+
     v) _VERBOSE="-v" ;;
+
     h) _help; exit 0 ;;
   esac
 done
@@ -286,12 +297,13 @@ if [ -n "$_PKG" ]; then
   esac
 fi
 
-echo "Primary options: $_POPT"
-echo "Secondary options: $_SOPT"
-echo "Options for operations: $_TOPT"
-echo "Extra params: $_PKG"
-echo "Verbose: $_VERBOSE"
-echo "Force: $_FORCE"
+# DEBUG
+# echo "Primary options: $_POPT"
+# echo "Secondary options: $_SOPT"
+# echo "Options for operations: $_TOPT"
+# echo "Extra params: $_PKG"
+# echo "Verbose: $_VERBOSE"
+# echo "Force: $_FORCE"
 
 # Return if no option was specified
 if [ -z "$_POPT" ]; then
@@ -305,57 +317,83 @@ case "$_POPT$_SOPT" in
         _exec_ DPKG     "dpkg-query -s $_PKG"
         _exec_ HOMEBREW "brew info $_PKG"
         _exec_ YUM      "yum info $_PKG"
+        _FORCE="" \
+            && _exec_ PORTAGE  "emerge --info $_PKG"
       ;;
    "Ql")
         _exec_ DPKG     "dpkg-query -L $_PKG"
         _exec_ HOMEBREW "brew list $_PKG"
         _exec_ YUM      "rpm -ql $_PKG"
+        _FORCE="" \
+            && (_exists "/usr/bin/qlist" && _exec_ PORTAGE "qlist $_PKG") \
+            || (_exists "/usr/bin/equery" && _exec_ PORTAGE "equery files $_PKG") \
+            || (_error "You need to install portage-utils or gentoolkit in order to perform this operation.")
       ;;
    "Qo")
         _exec_ DPKG     "dpkg-query -S $_PKG"
         _exec_ HOMEBREW "echo 'Error: function not implemented in homebrew'"
         _exec_ YUM      "rpm -qf $_PKG"
+        _FORCE="" \
+            && _exists "/usr/bin/equery" && _exec_ PORTAGE "equery belongs $_PKG" \
+                                         || _error "You need to install gentoolkit in order to perform this operation"
       ;;
    "Qp")
         # NOTE: input ($_PKG) should be a package
         _exec_ DPKG     "dpkg-deb -I $_PKG"
         _exec_ HOMEBREW "echo 'Error: function not implemented in homebrew'"
         _exec_ YUM      "rpm -qp $_PKG"
+        [ $_OSTYPE = "PORTAGE" ] && \
+            _error "Gentoo has no definition of 'package file', thus this feature is not supported."
       ;;
    "Qc")
-        _exec_ DPKG     "echo 'Error: function not implemented on Debian system'"
+        _exec_ DPKG     "echo 'Error: function not implemented in Debian system'"
         _exec_ HOMEBREW "brew log $_PKG"
         _exec_ YUM      "rpm -q --changelog $_PKG"
+        _FORCE="" \
+            && _exec_ PORTAGE "emerge -p --changelog $_PKG"
       ;;
    "Qu")
         _exec_ DPKG     "apt-get upgrade --trivial-only $_PKG"
         _exec_ HOMEBREW "brew outdated | grep $_PKG"
         _exec_ YUM      "yum list updates $_PKG"
+        _exec_ PORTAGE "emerge -uvN $_PKG" # not exactly
       ;;
    "Qm")
-        _exec_ DPKG     "echo 'Error: function not implemented on Debian system'"
+        _exec_ DPKG     "echo 'Error: function not implemented in Debian system'"
         _exec_ HOMEBREW "echo 'Error: function not implemented in homebrew'"
         _exec_ YUM      "yum list extras $_PKG"
+        [ $_OSTYPE = "PORTAGE" ] && \
+            _error "Not supported in Gentoo"
       ;;
     "Q")
         _exec_ DPKG     "dpkg -l $_PKG | grep -E ^[hi]i"
         _exec_ HOMEBREW "brew list | grep $_PKG"
         _exec_ YUM      "yum list installed $_PKG"
+
+        # There are actually many ways to do this in Gentoo
+        _FORCE="" \
+            && (_exists "/usr/bin/eix" && _exec_ PORTAGE "eix -I $_PKG") \
+            || (_exists "/usr/bin/equery" && _exec_ PORTAGE "equery list '*' $_PKG") \
+            || _exec_ PORTAGE "ls -d /var/db/pkg/*/*"
       ;;
    "Rs")
         _exec_ DPKG     "apt-get autoremove $_PKG"
         _exec_ HOMEBREW "echo 'Error: function not implemented in homebrew'"
         _exec_ YUM      "yum erase $_PKG"
+        _exec_ PORTAGE  "emerge --depclean world $_PKG"
       ;;
     "R")
         _exec_ DPKG     "apt-get remove $_PKG"
         _exec_ HOMEBREW "brew remove $_PKG"
         _exec_ YUM      "yum erase $_PKG"
+        _exec_ PORTAGE  "emerge --depclean $_PKG"
       ;;
    "Si")
         _exec_ DPKG     "dpkg-query -s $_PKG"
         _exec_ HOMEBREW "brew info $_PKG"
         _exec_ YUM      "yum info $_PKG"
+        _FORCE="" \
+            && _exec_ PORTAGE  "emerge --info $_PKG"
       ;;
   "Suy")
         _VERBOSE="" _exec_ DPKG "apt-get update"
@@ -363,36 +401,58 @@ case "$_POPT$_SOPT" in
         _exec_ HOMEBREW "brew update"
         _exec_ HOMEBREW "brew upgrade"
         _exec_ YUM "yum update"
+        [ "$_OSTYPE" = "PORTAGE" ] \
+            && (_exists "/usr/bin/layman" \
+                    && _exec_ PORTAGE "layman --sync-all && emerge --sync && emerge -auND world $_PKG" \
+                    || _exec_ PORTAGE "emerge --sync && emerge -uND world $_PKG" )
       ;;
    "Su")
         _VERBOSE="" _exec_ DPKG "apt-get upgrade"
-        _exec_ HOMEBREW "brew upgrade"
-        _exec_ YUM "yum update"
+        _exec_ HOMEBREW         "brew upgrade"
+        _exec_ YUM              "yum update"
+        _exec_ PORTAGE          "emerge -uND world $_PKG"
       ;;
    "Sy")
         _VERBOSE="" _exec_ DPKG "apt-get update"
-        _exec_ HOMEBREW "brew update"
-        _exec_ YUM "yum check-update"
+        _exec_ HOMEBREW         "brew update"
+        _exec_ YUM              "yum check-update"
+        [ "$_OSTYPE" = "PORTAGE" ] \
+            && _FORCE="" \
+            && (_exists "/usr/bin/layman" \
+                   && _exec_ PORTAGE "layman --sync-all && emerge --sync" \
+                   || _exec_ PORTAGE "emerge --sync" )
       ;;
    "Ss")
         _exec_ DPKG     "apt-cache search $_PKG"
         _exec_ HOMEBREW "brew search $_PKG"
         _exec_ YUM      "yum search $_PKG"
+        _FORCE="" \
+            && (_exists "/usr/bin/eix" && _exec_ PORTAGE "eix $_PKG" \
+                                       || _exec_ PORTAGE "emerge --search $_PKG") \
       ;;
    "Sc")
         _exec_ DPKG     "apt-get clean"
         _exec_ HOMEBREW "echo 'Error: function not implemented in homebrew'"
         _exec_ YUM      "yum clean expire-cache"
+        _FORCE="" \
+            && (_exists "/usr/bin/eclean-dist" && _exec_ PORTAGE "eclean-dist -d -t1m -s50 -f" \
+                                               || _error "You need install gentoolkit to perform this operation.")
       ;;
   "Scc")
         _exec_ DPKG     "apt-get autoclean"
         _exec_ HOMEBREW "echo 'Error: function not implemented in homebrew'"
         _exec_ YUM      "yum clean packages"
+        _FORCE="" \
+            && (_exists "/usr/bin/eclean" && _exec_ PORTAGE "eclean -i distfiles" \
+                                          || _error "You need install gentoolkit to perform this operation.")
+
       ;;
  "Sccc")
         _exec_ DPKG     "rm -fv /var/cache/apt/*.bin /var/cache/apt/archives/*.* /var/lib/apt/lists/*.*; apt-get autoclean"
         _exec_ HOMEBREW "echo 'Error: function not implemented in homebrew'"
         _exec_ YUM      "yum clean all"
+        _FORCE="" \
+            && _exec_ PORTAGE "rm -fv /usr/portage/distfiles/*.*"
       ;;
     "S")
         if [ -z "$_PKG" ]; then
@@ -402,11 +462,14 @@ case "$_POPT$_SOPT" in
           _exec_ DPKG     "apt-get install $_TOPT $_PKG"
           _exec_ HOMEBREW "brew install $_TOPT $_PKG"
           _exec_ YUM      "yum install $_TOPT $_PKG"
+          _exec_ PORTAGE  "emerge $_TOPT $_PKG"
         fi
       ;;
   "U")
-        _exec_ DPKG     "echo 'Error: function not implemented on Debian system'"
+        _exec_ DPKG     "echo 'Error: function not implemented in Debian system'"
         _exec_ HOMEBREW "echo 'Error: function not implemented in homebrew'"
         _exec_ YUM      "yum localinstall"
+        [ $_OSTYPE = "PORTAGE" ] && \
+            _error "You need to implement a local overlay and do the installation as usual."
       ;;
 esac
